version: '3.8'

services:
  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"